#import "NCDatabase.h"
#import "../Model/NCServerModels.h"
#import "../../Shared/NCRuntimePaths.h"
#import <sqlite3.h>
@interface NCDatabase () { sqlite3 *_db; dispatch_queue_t _queue; BOOL _started; } @end
@implementation NCDatabase
+ (instancetype)shared { static id x; static dispatch_once_t once; dispatch_once(&once,^{x=[self new];}); return x; }
- (instancetype)init { if ((self=[super init])) _queue=dispatch_queue_create("com.netcapture.db",DISPATCH_QUEUE_SERIAL); return self; }
- (BOOL)start { __block BOOL ok=NO; dispatch_sync(_queue,^{ if (self->_started) {ok=YES;return;} NSString *p=[NCRuntimePaths databasePath]; if (sqlite3_open_v2(p.fileSystemRepresentation,&self->_db,SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|SQLITE_OPEN_FULLMUTEX,NULL)!=SQLITE_OK) return; sqlite3_busy_timeout(self->_db,2000); const char *sql="PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,storage_id TEXT,session_id TEXT,connection_id TEXT,peer_uid INTEGER,peer_gid INTEGER,source INTEGER,task_id INTEGER,started_at REAL,ended_at REAL,complete INTEGER,ipc_loss INTEGER,cancel_requested INTEGER,failure_category INTEGER,error_domain TEXT,error_code INTEGER,error_description TEXT,termination_reason TEXT); CREATE TABLE IF NOT EXISTS hops(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL,hop_index INTEGER,started_at REAL,ended_at REAL,method TEXT,url TEXT,status_code INTEGER,request_headers TEXT,response_headers TEXT,response_body_path TEXT,response_body_total INTEGER,response_body_stored INTEGER,response_body_ipc_dropped INTEGER,response_body_truncated INTEGER,response_body_corrupted INTEGER,FOREIGN KEY(transaction_id) REFERENCES transactions(id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS idx_hops_tx_idx ON hops(transaction_id,hop_index);"; char *err=NULL; if (sqlite3_exec(self->_db,sql,NULL,NULL,&err)!=SQLITE_OK) { if(err)sqlite3_free(err); return; } self->_started=YES; ok=YES; }); return ok; }
static void bindText(sqlite3_stmt *s,int i,NSString *v){ if(v) sqlite3_bind_text(s,i,v.UTF8String,-1,SQLITE_TRANSIENT); else sqlite3_bind_null(s,i); }
static NSString *json(id obj){ if(!obj||![NSJSONSerialization isValidJSONObject:obj])return nil; NSData*d=[NSJSONSerialization dataWithJSONObject:obj options:0 error:nil]; return d?[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding]:nil; }
- (void)insertTransaction:(NCServerTransaction *)tx completion:(void(^)(BOOL))completion { dispatch_async(_queue,^{ BOOL ok=NO; if(!self->_started){if(completion)completion(NO);return;} if(sqlite3_exec(self->_db,"BEGIN IMMEDIATE",NULL,NULL,NULL)!=SQLITE_OK){if(completion)completion(NO);return;} sqlite3_stmt *s=NULL; const char *q="INSERT INTO transactions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; if(sqlite3_prepare_v2(self->_db,q,-1,&s,NULL)==SQLITE_OK){int i=1; bindText(s,i++,tx.identifier);bindText(s,i++,tx.storageIdentifier);bindText(s,i++,tx.sessionIdentifier);bindText(s,i++,tx.connectionIdentifier);sqlite3_bind_int64(s,i++,tx.peerUID);sqlite3_bind_int64(s,i++,tx.peerGID);sqlite3_bind_int64(s,i++,tx.source);sqlite3_bind_int64(s,i++,tx.taskIdentifier);sqlite3_bind_double(s,i++,tx.startedAt);sqlite3_bind_double(s,i++,tx.endedAt);sqlite3_bind_int(s,i++,tx.complete);sqlite3_bind_int(s,i++,tx.ipcLoss);sqlite3_bind_int(s,i++,tx.cancelRequested);sqlite3_bind_int64(s,i++,tx.failureCategory);bindText(s,i++,tx.errorDomain);sqlite3_bind_int64(s,i++,tx.errorCode);bindText(s,i++,tx.errorDescription);bindText(s,i++,tx.terminationReason); ok=sqlite3_step(s)==SQLITE_DONE;} if(s)sqlite3_finalize(s);
        if(ok){ const char *hq="INSERT INTO hops VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; for(NSString*hid in tx.hopOrder){NCServerHop*h=tx.hops[hid]; sqlite3_stmt*hs=NULL; if(sqlite3_prepare_v2(self->_db,hq,-1,&hs,NULL)!=SQLITE_OK){ok=NO;break;} int i=1; bindText(hs,i++,h.identifier);bindText(hs,i++,tx.identifier);sqlite3_bind_int64(hs,i++,h.index);sqlite3_bind_double(hs,i++,h.startedAt);sqlite3_bind_double(hs,i++,h.endedAt);bindText(hs,i++,h.method);bindText(hs,i++,h.URLString);sqlite3_bind_int64(hs,i++,h.statusCode);bindText(hs,i++,json(h.requestHeaders));bindText(hs,i++,json(h.responseHeaders));bindText(hs,i++,h.responseBody.path);sqlite3_bind_int64(hs,i++,MAX(h.responseBody.clientObservedBytes,h.responseBody.receivedBytes));sqlite3_bind_int64(hs,i++,h.responseBody.storedBytes);sqlite3_bind_int64(hs,i++,h.responseBody.ipcDroppedBytes);sqlite3_bind_int(hs,i++,h.responseBody.truncated);sqlite3_bind_int(hs,i++,h.responseBody.corrupted); if(sqlite3_step(hs)!=SQLITE_DONE)ok=NO; sqlite3_finalize(hs); if(!ok)break; }}
        sqlite3_exec(self->_db,ok?"COMMIT":"ROLLBACK",NULL,NULL,NULL); if(completion)completion(ok); }); }
@end
